### PR TITLE
add CUSTOM keybindings for additional UI hotkeys

### PR DESCRIPTION
**Pull request by myk002**
This will allow, among other things, Home, End, Ctrl+Left, and Ctrl+Right to be viable keys to move the text insertion cursor in text widgets.

I'll provide the text to append to interface.txt for the default mappings as well

### CODE REVIEW

**Comment by myk002** [comment]
Additions to `interface.txt`:
```
[BIND:CUSTOM_UP:REPEAT_FAST]
[SYM:0:Up]
[BIND:CUSTOM_DOWN:REPEAT_FAST]
[SYM:0:Down]
[BIND:CUSTOM_LEFT:REPEAT_FAST]
[SYM:0:Left]
[BIND:CUSTOM_RIGHT:REPEAT_FAST]
[SYM:0:Right]
[BIND:CUSTOM_TAB:REPEAT_NOT]
[SYM:0:Tab]
[BIND:CUSTOM_HOME:REPEAT_NOT]
[SYM:0:Home]
[BIND:CUSTOM_END:REPEAT_NOT]
[SYM:0:End]
[BIND:CUSTOM_PGUP:REPEAT_FAST]
[SYM:0:Page Up]
[BIND:CUSTOM_PGDN:REPEAT_FAST]
[SYM:0:Page Down]
[BIND:CUSTOM_INSERT:REPEAT_NOT]
[SYM:0:Insert]
[BIND:CUSTOM_DELETE:REPEAT_FAST]
[SYM:0:Delete]

[BIND:CUSTOM_SHIFT_ENTER:REPEAT_NOT]
[SYM:1:Enter]
[BIND:CUSTOM_SHIFT_UP:REPEAT_FAST]
[SYM:1:Up]
[BIND:CUSTOM_SHIFT_DOWN:REPEAT_FAST]
[SYM:1:Down]
[BIND:CUSTOM_SHIFT_LEFT:REPEAT_FAST]
[SYM:1:Left]
[BIND:CUSTOM_SHIFT_RIGHT:REPEAT_FAST]
[SYM:1:Right]
[BIND:CUSTOM_SHIFT_TAB:REPEAT_NOT]
[SYM:1:Tab]
[BIND:CUSTOM_SHIFT_HOME:REPEAT_NOT]
[SYM:1:Home]
[BIND:CUSTOM_SHIFT_END:REPEAT_NOT]
[SYM:1:End]
[BIND:CUSTOM_SHIFT_PGUP:REPEAT_FAST]
[SYM:1:Page Up]
[BIND:CUSTOM_SHIFT_PGDN:REPEAT_FAST]
[SYM:1:Page Down]
[BIND:CUSTOM_SHIFT_INSERT:REPEAT_NOT]
[SYM:1:Insert]
[BIND:CUSTOM_SHIFT_DELETE:REPEAT_FAST]
[SYM:1:Delete]

[BIND:CUSTOM_CTRL_ENTER:REPEAT_NOT]
[SYM:2:Enter]
[BIND:CUSTOM_CTRL_UP:REPEAT_FAST]
[SYM:2:Up]
[BIND:CUSTOM_CTRL_DOWN:REPEAT_FAST]
[SYM:2:Down]
[BIND:CUSTOM_CTRL_LEFT:REPEAT_FAST]
[SYM:2:Left]
[BIND:CUSTOM_CTRL_RIGHT:REPEAT_FAST]
[SYM:2:Right]
[BIND:CUSTOM_CTRL_TAB:REPEAT_NOT]
[SYM:2:Tab]
[BIND:CUSTOM_CTRL_HOME:REPEAT_NOT]
[SYM:2:Home]
[BIND:CUSTOM_CTRL_END:REPEAT_NOT]
[SYM:2:End]
[BIND:CUSTOM_CTRL_PGUP:REPEAT_FAST]
[SYM:2:Page Up]
[BIND:CUSTOM_CTRL_PGDN:REPEAT_FAST]
[SYM:2:Page Down]
[BIND:CUSTOM_CTRL_INSERT:REPEAT_NOT]
[SYM:2:Insert]
[BIND:CUSTOM_CTRL_DELETE:REPEAT_FAST]
[SYM:2:Delete]
[BIND:CUSTOM_CTRL_SLASH:REPEAT_NOT]
[SYM:2:/]
[BIND:CUSTOM_CTRL_0:REPEAT_NOT]
[SYM:2:0]
[BIND:CUSTOM_CTRL_1:REPEAT_NOT]
[SYM:2:1]
[BIND:CUSTOM_CTRL_2:REPEAT_NOT]
[SYM:2:2]
[BIND:CUSTOM_CTRL_3:REPEAT_NOT]
[SYM:2:3]
[BIND:CUSTOM_CTRL_4:REPEAT_NOT]
[SYM:2:4]
[BIND:CUSTOM_CTRL_5:REPEAT_NOT]
[SYM:2:5]
[BIND:CUSTOM_CTRL_6:REPEAT_NOT]
[SYM:2:6]
[BIND:CUSTOM_CTRL_7:REPEAT_NOT]
[SYM:2:7]
[BIND:CUSTOM_CTRL_8:REPEAT_NOT]
[SYM:2:8]
[BIND:CUSTOM_CTRL_9:REPEAT_NOT]
[SYM:2:9]

[BIND:CUSTOM_ALT_0:REPEAT_NOT]
[SYM:4:0]
[BIND:CUSTOM_ALT_1:REPEAT_NOT]
[SYM:4:1]
[BIND:CUSTOM_ALT_2:REPEAT_NOT]
[SYM:4:2]
[BIND:CUSTOM_ALT_3:REPEAT_NOT]
[SYM:4:3]
[BIND:CUSTOM_ALT_4:REPEAT_NOT]
[SYM:4:4]
[BIND:CUSTOM_ALT_5:REPEAT_NOT]
[SYM:4:5]
[BIND:CUSTOM_ALT_6:REPEAT_NOT]
[SYM:4:6]
[BIND:CUSTOM_ALT_7:REPEAT_NOT]
[SYM:4:7]
[BIND:CUSTOM_ALT_8:REPEAT_NOT]
[SYM:4:8]
[BIND:CUSTOM_ALT_9:REPEAT_NOT]
[SYM:4:9]
```

**Comment by Dragoon209** [comment]
+1 to this.  Specifically for the Ctrl+Arrows, Ctrl+Shift+Arrows, Ctrl+Delete and Ctrl+Backspace keyboard entries.  

lethosor already linked it (Thanks!) I described some of the use cases I see in another feature request: https://github.com/DFHack/dfhack/issues/3419

**Comment by myk002** [comment]
`interface.txt` additions updated in https://github.com/Putnam3145/Dwarf-Fortress--libgraphics--/pull/4#issuecomment-1501287586

**Review by Putnam3145 — APPROVED** [review]
Tested, seems fine--probably going to put a 24 hour approve-to-merge cycle in place for my own sanity (don't want to merge stuff and have people go "WAIT NO DON'T", which is an experience I have had myself too many times, haha)

**Comment by myk002** [comment]
Could this possibly get merged before the 50.12 release?

**Comment by lethosor** [comment]
This would also require updates to the default `interface.txt` for these keys to be functional, yes?

**Comment by Putnam3145** [comment]
Merged as of 51.01-beta20

**Pull request closed without merging**
